New home screen improved
OntimizeWeb/ontimize-web-ngx-playground pull request #178
Opened 2023-03-09 08:54 UTC by javierFernandezMendez

2023-03-09 18:24 UTC, daniel-grana approved these changes

2023-03-10 09:44 UTC, tomfacal submitted a review, later dismissed

2023-03-10 09:58 UTC, patricia-martinez-imatia requested changes

2023-03-10 09:58 UTC, patricia-martinez-imatia commented on src/app/main/home/home.component.html
> +      <o-button type="STROKED" label="CHANGELOG" layout-padding color="primary" icon="access_time"></o-button>
It need link url to CHANGELOG

2023-03-14 11:48 UTC, daniel-grana submitted a review, later dismissed

2023-03-15 08:55 UTC, patricia-martinez-imatia requested changes

2023-03-15 13:20 UTC, daniel-grana approved these changes

2023-03-16 09:05 UTC, merged