Data structure name refactored to screen configuration
OntimizeWeb/ontimize-web-ngx-playground pull request #207
Opened 2023-03-28 10:55 UTC by javierFernandezMendez

2023-03-29 09:12 UTC, daniel-grana approved these changes

2023-03-29 09:42 UTC, patricia-martinez-imatia requested changes

2023-03-29 09:42 UTC, patricia-martinez-imatia commented on src/app/main/data/lists/01.list-item-text/list-item-text.component.ts
> +  dataStructure: ScreenConfigurationComponent;
I think this variable dataStructure is not necessary

2023-03-29 09:42 UTC, patricia-martinez-imatia commented on src/app/main/data/lists/03.list-item-card/list-item-card.component.ts
> +  dataStructure: ScreenConfigurationComponent;
I think this variable dataStructure is not necessary

2023-03-29 09:42 UTC, patricia-martinez-imatia commented on src/app/main/data/lists/04.list-item-card-image/list-item-card-image.component.ts
> +  dataStructure: ScreenConfigurationComponent;
I think this variable dataStructure is not necessary

2023-03-29 09:42 UTC, patricia-martinez-imatia commented on src/app/main/data/table/02.fixed/table-fixed.component.ts
> +  dataStructure: ScreenConfigurationComponent;
I think this variable dataStructure is not necessary

2023-03-29 09:42 UTC, patricia-martinez-imatia commented on src/app/main/data/table/08.pagination/table-pagination.component.ts
> +  dataStructure: ScreenConfigurationComponent;
I think this variable dataStructure is not necessary

2023-03-29 10:20 UTC, patricia-martinez-imatia approved these changes

2023-03-30 08:28 UTC, daniel-grana approved these changes

2023-03-30 09:41 UTC, merged