Gallery example screen and list card fixes
OntimizeWeb/ontimize-web-ngx-playground pull request #217
Opened 2023-04-25 12:02 UTC by javierFernandezMendez

2023-04-27 11:39 UTC, daniel-grana submitted a review, later dismissed

2023-04-27 11:49 UTC, patricia-martinez-imatia commented on src/app/main/data/lists/lists.component.scss
> +img.mat-card-image.ng-star-inserted {
it is not recommended to use the scss classes generated by angular

2023-04-27 11:52 UTC, patricia-martinez-imatia requested changes

2023-04-27 11:52 UTC, patricia-martinez-imatia commented on src/styles.scss
> -list-item-card,
why did you remove this line?

2023-04-27 12:03 UTC, patricia-martinez-imatia requested changes

2023-04-27 12:03 UTC, patricia-martinez-imatia commented on src/app/shared/example/example.component.scss
> +    max-height: 50px;
I think it's redundant if the height is 50px

2023-05-02 10:47 UTC, daniel-grana approved these changes

2023-05-03 04:14 UTC, patricia-martinez-imatia approved these changes

2023-05-03 07:22 UTC, merged