[8.x.x] Table row expandable
OntimizeWeb/ontimize-web-ngx-playground pull request #46
Opened 2020-10-02 15:36 UTC by patricia-martinez-imatia

Examples of the row expandable

2020-10-05 05:55 UTC, daniel-grana requested changes

2020-10-05 05:55 UTC, daniel-grana commented on src/app/shared/services/dummy.service.ts
> +    // if (keys.length > 0 && resp.data && resp.data.length > 0) {
Remove unnecessary comments please

2020-10-05 05:55 UTC, daniel-grana commented on src/app/shared/services/dummy.service.ts
> +    // const dataObservable: Observable<any> = new Observable(_innerObserver => {
Remove unnecessary comments please

2020-10-05 13:52 UTC, daniel-grana approved these changes

2020-10-05 14:32 UTC, pacogomezimatia approved these changes

2020-10-07 09:11 UTC, manuel-cid approved these changes

2020-10-14 05:24 UTC, merged